# Generated by Django 5.0.1 on 2024-01-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geek',
            name='image',
            field=models.FileField(blank=True, upload_to='project_images/'),
        ),
    ]
